# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        # Get the repository's code
        - name: Checkout
          uses: actions/checkout@v2
        # https://github.com/docker/setup-qemu-action
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to GHCR
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Docker meta
          id: meta_id # you'll use this in the next step
          uses: docker/metadata-action@v3
          with:
          # list of Docker images to use as base name for tags
            images: |
              compass
            # Docker tags based on the following events/attributes
            tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=sha
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            platforms: linux/amd64,linux/arm/v7
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta_id.outputs.tags }}
            labels: ${{ steps.meta_id.outputs.labels }}